### PR TITLE
Add retries to download functions

### PR DESCRIPTION
**Pull request by tillywoodfield**
Add retries to top-level functions in `utils.download` to mitigate occasional connection errors.

https://github.com/codeforIATI/iatikit/issues/58

Also relates to https://github.com/codeforIATI/iati-tables/issues/37

### CODE REVIEW

**Comment by andylolz** [comment]
Adding a retry loop is definitely a good idea!

I think this can be done without an extra dependency, though… I’m pretty sure requests has something for retrying built in. Is that something you’d be happy to look at using, @tillywoodfield?

Happy for a PR, but I’d rather avoid the extra dependency if possible.

**Comment by tillywoodfield** [comment]
Hi @andylolz, no problem that makes sense, I'm happy to rework it

**Review by andylolz — APPROVED** [review]
Fab – thank you for this! Looks good to me.

**Comment by andylolz** [comment]
Version 3.4.0 is now on pypi, and includes this feature: https://pypi.org/project/iatikit/3.4.0/

**Comment by tillywoodfield** [comment]
Thanks @andylolz!

**Pull request merged**
